Improve make_optional_func_list and make renegotiation functions optional.
wolfSSL/wolfssl-py pull request #23
Opened 2021-12-10 01:27 UTC by haydenroche5

`make_optional_func_list` will fall back to using `nm` to determine if a
function is provided by libwolfssl if libwolfssl is a static library. This
commit makes it so we first check if `nm` is available. If it's not available,
the function will print a warning and assume all optional functions are
available.

2021-12-21 14:31 UTC, julek-wolfssl requested changes
Installing on a "fresh" PC I needed to run `sudo apt-get install python3-dev` (would be `sudo apt-get install python-dev` for python 2) for setup to succeed. Let's add that to the README.

+ The error I sent you directly.

2022-02-08 15:22 UTC, LinuxJedi commented
@haydenroche5 if you do loop back on this, can you think of a way of doing it without `nm`? This is pretty much the only blocker for me adding Windows support (Windows has a similar tool, but the path to it is different on pretty much every VS installation).

2022-02-08 16:17 UTC, haydenroche5 commented
> @haydenroche5 if you do loop back on this, can you think of a way of doing it without `nm`? This is pretty much the only blocker for me adding Windows support (Windows has a similar tool, but the path to it is different on pretty much every VS installation).

I think if there's no easy way to get the symbols reliably on Windows, then we'll just have to assume all the optional functions are available?

2022-02-10 14:43 UTC, LinuxJedi commented
> I think if there's no easy way to get the symbols reliably on Windows, then we'll just have to assume all the optional functions are available?

That or we have to do a macro detection thing like in wolfcrypt-py (which I'm guessing will be much more work). Probably best to just assume all optional are available in Windows.

2023-07-27 13:46 UTC, JacobBarthelmeh commented
https://github.com/wolfSSL/wolfssl-py/pull/43

2023-07-27 13:46 UTC, closed without merging