wolfssl-py: support disabling secure renegotiation
wolfSSL/wolfssl-py pull request #54
Opened 2024-08-19 16:20 UTC by rizlik

Use environment variable WOLFSSLPY_DISABLE_SCR to build with secure renegotiation disabled.

2024-08-19 16:29 UTC, julek-wolfssl requested changes

2024-08-19 16:29 UTC, julek-wolfssl commented on wolfssl/_build_ffi.py
> +    disable_scr = True if os.getenv("WOLFSSLPY_DISABLE_SCR") else False
`getenv` can have a default value https://docs.python.org/3/library/os.html#os.getenv.

2024-08-20 11:38 UTC, julek-wolfssl approved these changes

2024-08-23 21:50 UTC, douzzer approved these changes

2024-08-23 21:50 UTC, merged